import type { ScheduleItem, ScheduleSnapshot } from './types'

/**
 * Realistic — but entirely fictional — seed data for the SJ Invest shared
 * schedule / calendar. FCs, customers and teams reuse the FC OS / Customer
 * Workspace / Sales Activity seeds; all data is mock only, with no real personal
 * or sensitive information. Items span FC work schedules, customer follow-ups,
 * meetings and appointments, with mixed statuses, overdue follow-ups, today's
 * work, completed items and high-priority appointments.
 */

const at = (day: string, time: string): string => `${day}T${time}:00.000Z`

type Spec = Omit<ScheduleItem, 'createdAt' | 'updatedAt'>

const SPECS: Spec[] = [
  {
    scheduleId: 'sch-3001',
    kind: 'meeting',
    status: 'confirmed',
    priority: 'P1',
    title: '강남 1팀 아침 조회',
    description: '팀 목표 점검 및 오늘 활동 배분',
    fcId: 'fc-tl-gn1',
    fcName: '박민서',
    team: '강남 1팀',
    customerId: null,
    customerName: null,
    startAt: at('2026-07-02', '00:00'),
    endAt: at('2026-07-02', '00:30'),
    location: '강남 1팀 회의실',
    completedAt: null,
    result: '',
    nextAction: '팀원별 오늘 목표 공유',
    memo: '주간 실적 리뷰 포함'
  },
  {
    scheduleId: 'sch-3002',
    kind: 'appointment',
    status: 'confirmed',
    priority: 'P0',
    title: '윤서연 클로징 미팅',
    description: '건강종합 계약 클로징 대면 상담',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    team: '강남 1팀',
    customerId: 'cus-1002',
    customerName: '윤서연',
    startAt: at('2026-07-02', '02:00'),
    endAt: at('2026-07-02', '03:00'),
    location: '강남지점 상담실',
    completedAt: null,
    result: '',
    nextAction: '청약 및 계약 체결',
    memo: 'VIP 고객 — 우선 응대'
  },
  {
    scheduleId: 'sch-3003',
    kind: 'appointment',
    status: 'scheduled',
    priority: 'P1',
    title: '강민준 니즈 분석 미팅',
    description: '교육자금 설계 및 보장 분석 상담',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    team: '강남 1팀',
    customerId: 'cus-1001',
    customerName: '강민준',
    startAt: at('2026-07-02', '01:00'),
    endAt: at('2026-07-02', '02:00'),
    location: '강남 카페',
    completedAt: null,
    result: '',
    nextAction: '설계안 초안 작성',
    memo: '배우자 동반 상담 선호'
  },
  {
    scheduleId: 'sch-3004',
    kind: 'fc-schedule',
    status: 'in-progress',
    priority: 'P2',
    title: '최지아 오전 AP 콜 라운드',
    description: '신규 DB 대상 오전 AP 콜 30건',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    team: '강남 1팀',
    customerId: null,
    customerName: null,
    startAt: at('2026-07-02', '00:30'),
    endAt: at('2026-07-02', '01:00'),
    location: '강남지점',
    completedAt: null,
    result: '',
    nextAction: '관심 고객 1차 미팅 전환',
    memo: ''
  },
  {
    scheduleId: 'sch-3005',
    kind: 'customer-follow-up',
    status: 'missed',
    priority: 'P1',
    title: '박준호 후속 연락',
    description: 'DB 고객 재접촉 및 관심도 확인',
    fcId: 'fc-gn1-02',
    fcName: '한도윤',
    team: '강남 1팀',
    customerId: 'cus-1003',
    customerName: '박준호',
    startAt: at('2026-06-29', '05:00'),
    endAt: null,
    location: '전화',
    completedAt: null,
    result: '',
    nextAction: '오후 재통화',
    memo: '오후 시간대 통화 선호'
  },
  {
    scheduleId: 'sch-3006',
    kind: 'customer-follow-up',
    status: 'scheduled',
    priority: 'P2',
    title: '이하은 첫 접촉 콜',
    description: '온라인 상담 신청 고객 첫 연락',
    fcId: 'fc-gn1-02',
    fcName: '한도윤',
    team: '강남 1팀',
    customerId: 'cus-1004',
    customerName: '이하은',
    startAt: at('2026-07-02', '08:00'),
    endAt: null,
    location: '전화',
    completedAt: null,
    result: '',
    nextAction: '1차 미팅 일정 제안',
    memo: '사회초년생 — 소액 보장 위주'
  },
  {
    scheduleId: 'sch-3007',
    kind: 'appointment',
    status: 'in-progress',
    priority: 'P1',
    title: '한지민 증권 분석 상담',
    description: '보유 증권 분석 및 보장 공백 진단',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    team: '강남 2팀',
    customerId: 'cus-1006',
    customerName: '한지민',
    startAt: at('2026-07-02', '06:00'),
    endAt: at('2026-07-02', '07:00'),
    location: '강남 2팀 회의실',
    completedAt: null,
    result: '',
    nextAction: '진단비 보강 제안',
    memo: '실손만 보유, 진단비 니즈 큼'
  },
  {
    scheduleId: 'sch-3008',
    kind: 'customer-follow-up',
    status: 'scheduled',
    priority: 'P2',
    title: '정우성 기고객 관리 연락',
    description: '계약 후 정기 관리 및 소개 요청',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    team: '강남 2팀',
    customerId: 'cus-1005',
    customerName: '정우성',
    startAt: at('2026-07-02', '07:30'),
    endAt: null,
    location: '전화',
    completedAt: null,
    result: '',
    nextAction: '소개 고객 리스트 확보',
    memo: 'VIP — 소개 여력 높음'
  },
  {
    scheduleId: 'sch-3009',
    kind: 'appointment',
    status: 'confirmed',
    priority: 'P0',
    title: '김태리 클로징 미팅',
    description: '자녀사랑 + 건강 패키지 계약 클로징',
    fcId: 'fc-tl-gn1',
    fcName: '박민서',
    team: '강남 1팀',
    customerId: 'cus-1008',
    customerName: '김태리',
    startAt: at('2026-07-03', '07:00'),
    endAt: at('2026-07-03', '08:00'),
    location: '강남 1팀 회의실',
    completedAt: null,
    result: '',
    nextAction: '청약 진행',
    memo: '계약 의사 확인됨'
  },
  {
    scheduleId: 'sch-3010',
    kind: 'appointment',
    status: 'rescheduled',
    priority: 'P2',
    title: '서지우 2차 미팅',
    description: '자영업 소득보장 견적 재방문',
    fcId: 'fc-bd-tl',
    fcName: '서지호',
    team: '분당 1팀',
    customerId: 'cus-1009',
    customerName: '서지우',
    startAt: at('2026-07-04', '02:00'),
    endAt: at('2026-07-04', '03:00'),
    location: '분당지점',
    completedAt: null,
    result: '고객 일정 사유로 연기',
    nextAction: '재방문 일정 재조율',
    memo: '자영업 소득보장 니즈'
  },
  {
    scheduleId: 'sch-3011',
    kind: 'meeting',
    status: 'scheduled',
    priority: 'P2',
    title: '분당 1팀 주간 미팅',
    description: '주간 실적 점검 및 코칭',
    fcId: 'fc-bd-tl',
    fcName: '서지호',
    team: '분당 1팀',
    customerId: null,
    customerName: null,
    startAt: at('2026-07-03', '01:00'),
    endAt: at('2026-07-03', '02:00'),
    location: '분당지점 회의실',
    completedAt: null,
    result: '',
    nextAction: '팀원 코칭 노트 정리',
    memo: ''
  },
  {
    scheduleId: 'sch-3012',
    kind: 'appointment',
    status: 'completed',
    priority: 'P1',
    title: '정우성 종신 계약 체결',
    description: '평생종신 + 연금 계약 대면 체결',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    team: '강남 2팀',
    customerId: 'cus-1005',
    customerName: '정우성',
    startAt: at('2026-06-28', '04:00'),
    endAt: at('2026-06-28', '05:00'),
    location: '강남지점',
    completedAt: at('2026-06-28', '05:00'),
    result: '계약 체결 완료, 자녀 보험 추가 제안 예정',
    nextAction: '자녀 보험 제안 준비',
    memo: '가족 단위 리모델링 완료'
  },
  {
    scheduleId: 'sch-3013',
    kind: 'customer-follow-up',
    status: 'cancelled',
    priority: 'P3',
    title: '오세훈 재접촉 시도',
    description: '휴면 고객 재접촉 통화',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    team: '강남 2팀',
    customerId: 'cus-1007',
    customerName: '오세훈',
    startAt: at('2026-06-20', '01:00'),
    endAt: null,
    location: '전화',
    completedAt: null,
    result: '장기 무응답, 휴면 처리',
    nextAction: '',
    memo: ''
  },
  {
    scheduleId: 'sch-3014',
    kind: 'fc-schedule',
    status: 'scheduled',
    priority: 'P2',
    title: '최지아 오후 고객 서류 정리',
    description: '청약 서류 및 설계안 정리',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    team: '강남 1팀',
    customerId: null,
    customerName: null,
    startAt: at('2026-07-02', '09:00'),
    endAt: at('2026-07-02', '10:00'),
    location: '강남지점',
    completedAt: null,
    result: '',
    nextAction: '미결 서류 상신',
    memo: ''
  },
  {
    scheduleId: 'sch-3015',
    kind: 'customer-follow-up',
    status: 'scheduled',
    priority: 'P2',
    title: '김태리 소개 고객 컨택',
    description: '계약 후 지인 소개 요청 후속',
    fcId: 'fc-tl-gn1',
    fcName: '박민서',
    team: '강남 1팀',
    customerId: 'cus-1008',
    customerName: '김태리',
    startAt: at('2026-07-05', '02:00'),
    endAt: null,
    location: '전화',
    completedAt: null,
    result: '',
    nextAction: '소개 고객 리스트 확보',
    memo: '맞벌이 커뮤니티 소개 여력'
  }
]

export const scheduleSeed: ScheduleSnapshot = {
  items: SPECS.map<ScheduleItem>((spec) => ({
    ...spec,
    createdAt: at('2026-07-01', '00:00'),
    updatedAt: at('2026-07-01', '00:00')
  })),
  selectedScheduleId: 'sch-3002',
  eventLog: []
}
