import type { SalesActivity, SalesActivitySnapshot } from './types'

/**
 * Realistic — but entirely fictional — seed data for the SJ Invest sales
 * activity heartbeat. FCs, customers, teams and figures reuse the FC OS /
 * Customer Workspace seeds; all data is mock only, with no real personal or
 * sensitive information. Activities span AP / 1차 / 2차 / 증권분석 / 제안 /
 * 클로징 / 기고객관리, with mixed statuses, overdue follow-ups, today's work,
 * completed items and high-priority closings.
 */

const TODAY = '2026-07-02'
const at = (time: string): string => `${TODAY}T${time}:00.000Z`

type Spec = Omit<SalesActivity, 'createdAt' | 'updatedAt'>

const SPECS: Spec[] = [
  {
    activityId: 'act-2001',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    customerId: null,
    customerName: null,
    team: '강남 1팀',
    type: 'AP',
    status: 'planned',
    priority: 'P2',
    title: '오전 AP 콜 30건',
    description: '신규 DB 대상 오전 AP 콜 라운드',
    scheduledAt: at('00:30'),
    completedAt: null,
    result: '',
    nextAction: '관심 고객 1차 미팅 전환',
    nextActionAt: at('05:00'),
    memo: '',
    location: '강남지점',
    relatedConsultationStage: 'first-contact'
  },
  {
    activityId: 'act-2002',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    customerId: 'cus-1001',
    customerName: '강민준',
    team: '강남 1팀',
    type: 'first-meeting',
    status: 'completed',
    priority: 'P1',
    title: '강민준 1차 미팅',
    description: '가족 재무 상황 파악 및 니즈 청취',
    scheduledAt: '2026-06-22T05:00:00.000Z',
    completedAt: '2026-06-22T06:00:00.000Z',
    result: '교육자금 + 보장성 니즈 확인, 2차 진행 합의',
    nextAction: '니즈 분석 미팅 준비',
    nextActionAt: at('01:00'),
    memo: '배우자 동반 상담 선호',
    location: '강남 카페',
    relatedConsultationStage: 'needs-analysis'
  },
  {
    activityId: 'act-2003',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    customerId: 'cus-1001',
    customerName: '강민준',
    team: '강남 1팀',
    type: 'needs-analysis',
    status: 'planned',
    priority: 'P1',
    title: '강민준 니즈 분석',
    description: '교육자금 설계 및 보장 분석',
    scheduledAt: at('01:00'),
    completedAt: null,
    result: '',
    nextAction: '설계안 초안 작성',
    nextActionAt: at('07:00'),
    memo: '',
    location: '강남지점',
    relatedConsultationStage: 'needs-analysis'
  },
  {
    activityId: 'act-2004',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    customerId: 'cus-1002',
    customerName: '윤서연',
    team: '강남 1팀',
    type: 'proposal',
    status: 'completed',
    priority: 'P1',
    title: '윤서연 건강보험 제안',
    description: '건강종합 설계안 제안서 발송',
    scheduledAt: '2026-07-01T06:00:00.000Z',
    completedAt: '2026-07-01T06:30:00.000Z',
    result: '제안 수락 긍정적, 클로징 일정 협의',
    nextAction: '클로징 미팅',
    nextActionAt: at('02:00'),
    memo: '가족 상담 연계 가능',
    location: '온라인',
    relatedConsultationStage: 'proposal'
  },
  {
    activityId: 'act-2005',
    fcId: 'fc-gn1-01',
    fcName: '최지아',
    customerId: 'cus-1002',
    customerName: '윤서연',
    team: '강남 1팀',
    type: 'closing',
    status: 'planned',
    priority: 'P0',
    title: '윤서연 클로징',
    description: '건강종합 계약 클로징 미팅',
    scheduledAt: at('02:00'),
    completedAt: null,
    result: '',
    nextAction: '청약 및 계약 체결',
    nextActionAt: at('03:00'),
    memo: 'VIP 고객 — 우선 응대',
    location: '강남지점',
    relatedConsultationStage: 'closing'
  },
  {
    activityId: 'act-2006',
    fcId: 'fc-gn1-02',
    fcName: '한도윤',
    customerId: 'cus-1003',
    customerName: '박준호',
    team: '강남 1팀',
    type: 'follow-up',
    status: 'needs-follow-up',
    priority: 'P1',
    title: '박준호 후속 연락',
    description: 'DB 고객 재접촉 및 관심도 확인',
    scheduledAt: '2026-06-28T05:00:00.000Z',
    completedAt: null,
    result: '',
    nextAction: '오후 재통화',
    nextActionAt: '2026-06-29T05:00:00.000Z',
    memo: '오후 시간대 통화 선호',
    location: '전화',
    relatedConsultationStage: 'first-contact'
  },
  {
    activityId: 'act-2007',
    fcId: 'fc-gn1-02',
    fcName: '한도윤',
    customerId: 'cus-1004',
    customerName: '이하은',
    team: '강남 1팀',
    type: 'AP',
    status: 'planned',
    priority: 'P2',
    title: '이하은 첫 접촉 콜',
    description: '온라인 상담 신청 고객 첫 연락',
    scheduledAt: at('08:00'),
    completedAt: null,
    result: '',
    nextAction: '1차 미팅 일정 제안',
    nextActionAt: at('08:30'),
    memo: '사회초년생 — 소액 보장 위주',
    location: '전화',
    relatedConsultationStage: 'first-contact'
  },
  {
    activityId: 'act-2008',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    customerId: 'cus-1005',
    customerName: '정우성',
    team: '강남 2팀',
    type: 'contract',
    status: 'completed',
    priority: 'P1',
    title: '정우성 종신 계약',
    description: '평생종신 + 연금 계약 체결',
    scheduledAt: '2026-06-28T04:00:00.000Z',
    completedAt: '2026-06-28T05:00:00.000Z',
    result: '계약 체결 완료, 자녀 보험 추가 제안 예정',
    nextAction: '자녀 보험 제안 준비',
    nextActionAt: '2026-08-01T01:00:00.000Z',
    memo: '가족 단위 리모델링 완료',
    location: '강남지점',
    relatedConsultationStage: 'contract'
  },
  {
    activityId: 'act-2009',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    customerId: 'cus-1006',
    customerName: '한지민',
    team: '강남 2팀',
    type: 'policy-review',
    status: 'in-progress',
    priority: 'P1',
    title: '한지민 증권 분석',
    description: '보유 증권 분석 및 보장 공백 진단',
    scheduledAt: at('06:00'),
    completedAt: null,
    result: '',
    nextAction: '진단비 보강 제안',
    nextActionAt: at('09:00'),
    memo: '실손만 보유, 진단비 니즈 큼',
    location: '강남 2팀 회의실',
    relatedConsultationStage: 'policy-review'
  },
  {
    activityId: 'act-2010',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    customerId: 'cus-1005',
    customerName: '정우성',
    team: '강남 2팀',
    type: 'existing-customer-care',
    status: 'planned',
    priority: 'P2',
    title: '정우성 기고객 관리',
    description: '계약 후 정기 관리 및 소개 요청',
    scheduledAt: at('07:30'),
    completedAt: null,
    result: '',
    nextAction: '소개 고객 리스트 확보',
    nextActionAt: at('08:00'),
    memo: 'VIP — 소개 여력 높음',
    location: '전화',
    relatedConsultationStage: 'after-care'
  },
  {
    activityId: 'act-2011',
    fcId: 'fc-gn2-01',
    fcName: '임하준',
    customerId: 'cus-1007',
    customerName: '오세훈',
    team: '강남 2팀',
    type: 'follow-up',
    status: 'no-show',
    priority: 'P3',
    title: '오세훈 재접촉 시도',
    description: '휴면 고객 재접촉 통화',
    scheduledAt: '2026-06-20T01:00:00.000Z',
    completedAt: null,
    result: '무응답',
    nextAction: '문자 발송 후 보류',
    nextActionAt: null,
    memo: '장기 무응답, 휴면 처리',
    location: '전화',
    relatedConsultationStage: 'first-contact'
  },
  {
    activityId: 'act-2012',
    fcId: 'fc-tl-gn1',
    fcName: '박민서',
    customerId: 'cus-1008',
    customerName: '김태리',
    team: '강남 1팀',
    type: 'closing',
    status: 'planned',
    priority: 'P0',
    title: '김태리 클로징',
    description: '자녀사랑 + 건강 패키지 계약 클로징',
    scheduledAt: at('07:00'),
    completedAt: null,
    result: '',
    nextAction: '청약 진행',
    nextActionAt: at('08:00'),
    memo: '내일 계약 예정, 계약 의사 확인됨',
    location: '강남 1팀 회의실',
    relatedConsultationStage: 'closing'
  },
  {
    activityId: 'act-2013',
    fcId: 'fc-bd-tl',
    fcName: '서지호',
    customerId: 'cus-1009',
    customerName: '서지우',
    team: '분당 1팀',
    type: 'second-meeting',
    status: 'delayed',
    priority: 'P2',
    title: '서지우 2차 미팅',
    description: '자영업 소득보장 견적 재방문',
    scheduledAt: '2026-06-30T02:00:00.000Z',
    completedAt: null,
    result: '고객 일정 사유로 연기',
    nextAction: '재방문 일정 재조율',
    nextActionAt: at('02:00'),
    memo: '자영업 소득보장 니즈',
    location: '분당지점',
    relatedConsultationStage: 'needs-analysis'
  },
  {
    activityId: 'act-2014',
    fcId: 'fc-bd-tl',
    fcName: '서지호',
    customerId: 'cus-1010',
    customerName: '문가영',
    team: '분당 1팀',
    type: 'proposal',
    status: 'cancelled',
    priority: 'P3',
    title: '문가영 제안 재시도',
    description: '가격 비교 후 이탈 고객 재제안',
    scheduledAt: '2026-06-11T05:00:00.000Z',
    completedAt: null,
    result: '타사 계약으로 취소',
    nextAction: '리마케팅 후보 등록',
    nextActionAt: null,
    memo: '가격 민감 고객',
    location: '온라인',
    relatedConsultationStage: 'proposal'
  },
  {
    activityId: 'act-2015',
    fcId: 'fc-tl-gn1',
    fcName: '박민서',
    customerId: 'cus-1008',
    customerName: '김태리',
    team: '강남 1팀',
    type: 'referral-request',
    status: 'planned',
    priority: 'P2',
    title: '김태리 소개 요청',
    description: '계약 후 지인 소개 요청',
    scheduledAt: at('09:00'),
    completedAt: null,
    result: '',
    nextAction: '소개 고객 컨택',
    nextActionAt: at('09:30'),
    memo: '맞벌이 커뮤니티 소개 여력',
    location: '전화',
    relatedConsultationStage: 'after-care'
  }
]

export const salesActivitySeed: SalesActivitySnapshot = {
  activities: SPECS.map<SalesActivity>((spec) => ({
    ...spec,
    createdAt: at('00:00'),
    updatedAt: at('00:00')
  })),
  selectedActivityId: 'act-2005',
  eventLog: []
}
